[package]
name = "time_rouletto"
version = "0.1.0"
authors = ["GMNDS gabriel@gmnds.com"]
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib"]
